### ISSUE TITLE
ArrayGenerator skipping empty translations

### ISSUE THREAD

**Issue by jonasraoni** [php-gettext/Translator#3]
Hi!

Is it possible to update the `ArrayGenerator` to include empty translations? If yes, then I might create a PR in case it helps.
e.g.:
```
msgid "key"
msgstr ""
```

**Comment by oscarotero** [comment]
Yes, sure, thanks for contributing!
It should be configurable (with a property or an array), to prevent breaking changes. For example:

```php
$generator = new ArrayGenerator(["includeEmpty" => true]);
```

**Comment by jonasraoni** [comment]
Okay, I've used the signature that you recommended. Here's the PR :)

- https://github.com/php-gettext/Translator/pull/4
