### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by grandeljay** [php-gettext/Translator#6]
Sorry, I am unable to make this work, can you please tell me what I am doing wrong?

```php
use Gettext\GettextTranslator;

$t = new GettextTranslator();
$t->setLanguage('de_DE');
$t->loadDomain('messages', ROOT . '/Locale');

echo $t->gettext('Welcome to wishthis');
```

## `/Locale/de_DE/LC_MESSAGES/messages.po` (created with Poedit)
```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2022-03-21 09:58+0100\n"
"PO-Revision-Date: \n"
"Last-Translator: Jay Trees <github.jay@grandel.anonaddy.me>\n"
"Language-Team: \n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 3.0.1\n"
"X-Poedit-Basepath: ../../../src\n"
"X-Poedit-KeywordsList: __\n"
"X-Poedit-SearchPath-0: .\n"

#: functions/gettext.php:13 pages/home.php:22
msgid "Welcome to wishthis"
msgstr "Willkommen zu wishthis"
```

## `home.php`
```html
<h2 class="ui header"><?= _('Welcome to wishthis') ?></h2>
```

## What's wrong?
The text is not translated, the original is shown when I am expecting the German version.

**Comment by oscarotero** [comment]
To use the GettextTranslator, the translations file must be in `.mo` format.
The example in the README.md was wrong, sorry. I just fixed it.

**Comment by grandeljay** [comment]
Hey, thanks!

Unfortunately, after generating an `.mo` file I haven't noticed a difference yet.

In an attempt to get more insight I dumped the `GettextTranslator` but it's empty, do you have any more ideas for me? :/

```php
use Gettext\GettextTranslator;

$t = new GettextTranslator();
$t->setLanguage('de_DE');
$t->loadDomain('messages', ROOT . '/Locale');

var_dump($t);
```

Is empty
```
object(Gettext\GettextTranslator)#4 (0) {
}
```

**Comment by oscarotero** [comment]
The `GettextTranslator` is just a wrapper of the [native Gettext extension for PHP](https://www.php.net/manual/en/book.gettext.php) to provide the same interface as the regular translator. If you see [the code](https://github.com/php-gettext/Translator/blob/master/src/GettextTranslator.php#L67) you will notice that internally uses the `gettext` and `ngettext` functions of PHP. This is why it's empty: the translations in the .mo file are loaded by the gettext extension, not by this class.

Problems with the native gettext extension are very common (it depends on the locales installed in your operating system, if you change the mo file, you have to reload the server to clear the cache, etc). So maybe it's easy to use the regular translator (a bit less performance but more easy to use).

**Comment by grandeljay** [comment]
Reloading the web server solved the issue, thanks for helping out!
